# Generated by Django 6.0.5 on 2026-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_soon_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
